# Generated by Django 3.1.14 on 2023-09-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20230924_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.pokemon', verbose_name='Тип покемона'),
        ),
    ]
